### ISSUE TITLE
Adding pendo class name to class tag that has some classes already doesnt add space

### ISSUE THREAD

**Issue by TomislavMedved** [pgarzina/pendo-helper#1]
If you add a pendo class name with command to a class tag that already has some classes in it, class will be added connected to the previuous class.

etc. in example where we have class="t-uppercase" and want to add a pendo class name, we navigate mouse behind t-uppercase and add a class, class is connected to "t-uppercase". We can add space manually but if we use prettier, it is automatically activated (in my vs code setup) that when you focus out of the document that it runs, therefore it removes the space that we have just added before we perform a pendo action by ctrl shift + p

It would be nice if we could register the text before the mouse selector and based on that add space if needed.

**Comment by pgarzina** [comment]
Resolved in https://github.com/pgarzina/pendo-helper/pull/2
